2024-06-20 13:06:21,937 INFO     
Heat Source, Copyright (C) 2000-2019, Oregon Department of Environmental Quality

This program comes with ABSOLUTELY NO WARRANTY. Appropriate model 
use and application are the sole responsibility of the user. 
This is free software, and you are welcome to redistribute it under 
certain conditions described in the License.

Heat Source Version:  9.0.0b26

2024-06-20 13:06:21,937 INFO     Starting Model Initialization
2024-06-20 13:06:21,937 INFO     Reading control file
2024-06-20 13:06:21,961 ERROR    Error: Traceback (most recent call last):
  File "C:\Users\RIPHAWK\anaconda3\envs\py3810\lib\site-packages\heatsource9\BigRedButton.py", line 279, in run
    HSP = ModelControl(model_dir, control_file, 0)
  File "C:\Users\RIPHAWK\anaconda3\envs\py3810\lib\site-packages\heatsource9\BigRedButton.py", line 99, in __init__
    self.HS = ModelSetup(model_dir, control_file, run_type)
  File "C:\Users\RIPHAWK\anaconda3\envs\py3810\lib\site-packages\heatsource9\ModelSetup\ModelSetup.py", line 81, in __init__
    self.get_boundary_conditions()
  File "C:\Users\RIPHAWK\anaconda3\envs\py3810\lib\site-packages\heatsource9\ModelSetup\ModelSetup.py", line 192, in get_boundary_conditions
    data = self.inputs.import_bc()
  File "C:\Users\RIPHAWK\anaconda3\envs\py3810\lib\site-packages\heatsource9\ModelSetup\Inputs.py", line 252, in import_bc
    data = self.read_to_dict(IniParams["inputdir"],
  File "C:\Users\RIPHAWK\anaconda3\envs\py3810\lib\site-packages\heatsource9\ModelSetup\Inputs.py", line 729, in read_csv_to_dict
    with open(join(inputdir, filename.strip()), "rU") as file_object:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Ben_wd\\THESIS\\heatsource\\post_defense\\calibration\\ManningsN\\inputs\\WFK23_boundary.csv'

